package config

import (
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()

	if cfg.Hotkey.Binding != "Super+Shift+S" {
		t.Errorf("Hotkey.Binding = %q, want %q", cfg.Hotkey.Binding, "Super+Shift+S")
	}
	if cfg.Hotkey.MeetingBinding != "Super+Shift+X" {
		t.Errorf("Hotkey.MeetingBinding = %q, want %q", cfg.Hotkey.MeetingBinding, "Super+Shift+X")
	}
	if cfg.Audio.Device != "default" {
		t.Errorf("Audio.Device = %q, want %q", cfg.Audio.Device, "default")
	}
	if cfg.Transcription.GPUEnabled {
		t.Error("Transcription.GPUEnabled = true, want false (default)")
	}
	if cfg.Transcription.ModelPath == "" {
		t.Error("Transcription.ModelPath is empty")
	}
	if !cfg.Output.AutoPaste {
		t.Error("Output.AutoPaste = false, want true")
	}
	if !cfg.Output.Clipboard {
		t.Error("Output.Clipboard = false, want true")
	}
	if cfg.Output.SilenceTimeout != 5.0 {
		t.Errorf("Output.SilenceTimeout = %v, want 5.0", cfg.Output.SilenceTimeout)
	}
	// Phase 2 meeting defaults
	if cfg.Meeting.DefaultSources != "both" {
		t.Errorf("Meeting.DefaultSources = %q, want %q", cfg.Meeting.DefaultSources, "both")
	}
	if cfg.Meeting.SpeakerThreshold != 0.65 {
		t.Errorf("Meeting.SpeakerThreshold = %v, want 0.65", cfg.Meeting.SpeakerThreshold)
	}
	if !cfg.Meeting.AutoSave {
		t.Error("Meeting.AutoSave = false, want true")
	}
}

func TestSaveAndLoad(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	original := &Config{
		Hotkey: HotkeyConfig{Binding: "Ctrl+Alt+T"},
		Audio:  AudioConfig{Device: "hw:0,0"},
		Transcription: TranscriptionConfig{
			GPUEnabled: true,
			ModelPath:  "/custom/models",
		},
		Output: OutputConfig{
			AutoPaste:      false,
			Clipboard:      true,
			SilenceTimeout: 3.5,
		},
	}

	if err := Save(original, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	if loaded.Hotkey.Binding != original.Hotkey.Binding {
		t.Errorf("Hotkey.Binding = %q, want %q", loaded.Hotkey.Binding, original.Hotkey.Binding)
	}
	if loaded.Audio.Device != original.Audio.Device {
		t.Errorf("Audio.Device = %q, want %q", loaded.Audio.Device, original.Audio.Device)
	}
	if loaded.Transcription.GPUEnabled != original.Transcription.GPUEnabled {
		t.Errorf("Transcription.GPUEnabled = %v, want %v", loaded.Transcription.GPUEnabled, original.Transcription.GPUEnabled)
	}
	if loaded.Transcription.ModelPath != original.Transcription.ModelPath {
		t.Errorf("Transcription.ModelPath = %q, want %q", loaded.Transcription.ModelPath, original.Transcription.ModelPath)
	}
	if loaded.Output.AutoPaste != original.Output.AutoPaste {
		t.Errorf("Output.AutoPaste = %v, want %v", loaded.Output.AutoPaste, original.Output.AutoPaste)
	}
	if loaded.Output.Clipboard != original.Output.Clipboard {
		t.Errorf("Output.Clipboard = %v, want %v", loaded.Output.Clipboard, original.Output.Clipboard)
	}
	if loaded.Output.SilenceTimeout != original.Output.SilenceTimeout {
		t.Errorf("Output.SilenceTimeout = %v, want %v", loaded.Output.SilenceTimeout, original.Output.SilenceTimeout)
	}
}

func TestSaveCreatesDirectories(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "dirs", "config.toml")

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Error("Save() did not create the file")
	}
}

func TestSaveIncludesHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error: %v", err)
	}

	if !strings.HasPrefix(string(data), "# Generated by tomoe auto-init on ") {
		t.Error("Save() output missing header comment")
	}
}

func TestLoadNonexistent(t *testing.T) {
	_, err := Load("/nonexistent/path/config.toml")
	if err == nil {
		t.Error("Load() should return error for nonexistent file")
	}
}

func TestLoadInvalidTOML(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "bad.toml")

	if err := os.WriteFile(path, []byte("not valid [[ toml"), 0o644); err != nil {
		t.Fatalf("WriteFile() error: %v", err)
	}

	_, err := Load(path)
	if err == nil {
		t.Error("Load() should return error for invalid TOML")
	}
}

func TestPathRespectsXDGConfigHome(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "/custom/config")
	got := Path()
	want := "/custom/config/tomoe/config.toml"
	if got != want {
		t.Errorf("Path() = %q, want %q", got, want)
	}
}

func TestPathDefaultsToHome(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "")
	got := Path()
	if !strings.HasSuffix(got, filepath.Join(".config", "tomoe", "config.toml")) {
		t.Errorf("Path() = %q, want suffix %q", got, ".config/tomoe/config.toml")
	}
}

func TestModelDirRespectsXDGDataHome(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "/custom/data")
	got := ModelDir()
	want := "/custom/data/tomoe/models"
	if got != want {
		t.Errorf("ModelDir() = %q, want %q", got, want)
	}
}

func TestModelDirDefaultsToHome(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "")
	got := ModelDir()
	if !strings.HasSuffix(got, filepath.Join(".local", "share", "tomoe", "models")) {
		t.Errorf("ModelDir() = %q, want suffix %q", got, ".local/share/tomoe/models")
	}
}

func TestBackwardCompatPhase1Config(t *testing.T) {
	// A Phase 1 config (without [meeting] section) should load without error
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	phase1Config := `[hotkey]
binding = "Super+Shift+R"

[audio]
device = "default"

[transcription]
gpu_enabled = true
model_path = "/home/user/.local/share/tomoe/models"

[output]
auto_paste = true
clipboard = true
`
	if err := os.WriteFile(path, []byte(phase1Config), 0o644); err != nil {
		t.Fatalf("WriteFile() error: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error loading Phase 1 config: %v", err)
	}

	if cfg.Hotkey.Binding != "Super+Shift+R" {
		t.Errorf("Hotkey.Binding = %q, want %q", cfg.Hotkey.Binding, "Super+Shift+R")
	}
	if !cfg.Transcription.GPUEnabled {
		t.Error("GPUEnabled should be true")
	}
	// Meeting section absent from TOML — should get defaults (not zero values)
	if cfg.Meeting.DefaultSources != "both" {
		t.Errorf("Meeting.DefaultSources = %q, want %q (default)", cfg.Meeting.DefaultSources, "both")
	}
	if cfg.Meeting.SpeakerThreshold != 0.65 {
		t.Errorf("Meeting.SpeakerThreshold = %v, want 0.65 (default)", cfg.Meeting.SpeakerThreshold)
	}
	if !cfg.Meeting.AutoDetect {
		t.Error("Meeting.AutoDetect = false, want true (default)")
	}
}

func TestSessionDir(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "/custom/data")
	got := SessionDir()
	want := "/custom/data/tomoe/sessions"
	if got != want {
		t.Errorf("SessionDir() = %q, want %q", got, want)
	}
}

func TestHintAnalysisDir(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "/custom/data")
	if got, want := HintAnalysisDir(), "/custom/data/tomoe/hint-analysis"; got != want {
		t.Errorf("HintAnalysisDir() = %q, want %q", got, want)
	}
}

func TestSilenceTimeoutRoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	cfg.Output.SilenceTimeout = 7.25

	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	// Verify the TOML file contains the silence_timeout key
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error: %v", err)
	}
	if !strings.Contains(string(data), "silence_timeout") {
		t.Error("saved TOML does not contain silence_timeout key")
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if loaded.Output.SilenceTimeout != 7.25 {
		t.Errorf("Output.SilenceTimeout = %v, want 7.25", loaded.Output.SilenceTimeout)
	}
}

func TestSilenceTimeoutZeroRoundTrip(t *testing.T) {
	// SilenceTimeout of 0 means disabled; verify it round-trips correctly
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	cfg.Output.SilenceTimeout = 0

	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if loaded.Output.SilenceTimeout != 0 {
		t.Errorf("Output.SilenceTimeout = %v, want 0 (disabled)", loaded.Output.SilenceTimeout)
	}
}

func TestBackwardCompatNoSilenceTimeout(t *testing.T) {
	// A config TOML written before SilenceTimeout was added should parse without error.
	// The SilenceTimeout field should get its zero value (0).
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	oldConfig := `[hotkey]
binding = "Super+Shift+R"

[audio]
device = "default"

[transcription]
gpu_enabled = false
model_path = "/home/user/.local/share/tomoe/models"

[output]
auto_paste = true
clipboard = true
`
	if err := os.WriteFile(path, []byte(oldConfig), 0o644); err != nil {
		t.Fatalf("WriteFile() error: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	// Existing fields should parse correctly
	if !cfg.Output.AutoPaste {
		t.Error("Output.AutoPaste = false, want true")
	}
	if !cfg.Output.Clipboard {
		t.Error("Output.Clipboard = false, want true")
	}
	// SilenceTimeout absent from TOML — should get default (not zero)
	if cfg.Output.SilenceTimeout != 5.0 {
		t.Errorf("Output.SilenceTimeout = %v, want 5.0 (default)", cfg.Output.SilenceTimeout)
	}
}

func TestExistsWhenFilePresent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "tomoe", "config.toml")

	t.Setenv("XDG_CONFIG_HOME", dir)

	if Exists() {
		t.Error("Exists() = true before config file is created")
	}

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	if !Exists() {
		t.Error("Exists() = false after config file is created")
	}
}

func TestNewPipelineOptionsDefaultOffForExistingConfigs(t *testing.T) {
	// A config written before two-pass and the clustering rules existed
	// keeps main's behavior: every new option defaults to off.
	path := filepath.Join(t.TempDir(), "config.toml")
	old := "[transcription]\ngpu_enabled = true\n\n[meeting]\nspeaker_threshold = 0.65\n"
	if err := os.WriteFile(path, []byte(old), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Transcription.TwoPass {
		t.Error("Transcription.TwoPass = true, want false (default)")
	}
	if cfg.Meeting.StickyThresholdMargin != 0 {
		t.Errorf("Meeting.StickyThresholdMargin = %v, want 0 (rule off by default)", cfg.Meeting.StickyThresholdMargin)
	}
	if cfg.Meeting.MinAssignDuration != 0 {
		t.Errorf("Meeting.MinAssignDuration = %v, want 0 (rule off by default)", cfg.Meeting.MinAssignDuration)
	}
}

func TestNewPipelineOptionsOptIn(t *testing.T) {
	path := filepath.Join(t.TempDir(), "config.toml")
	cfgText := "[transcription]\ntwo_pass = true\n\n[meeting]\nsticky_threshold_margin = 0.15\nmin_assign_duration = 0.7\n"
	if err := os.WriteFile(path, []byte(cfgText), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if !cfg.Transcription.TwoPass {
		t.Error("Transcription.TwoPass = false, want true")
	}
	if cfg.Meeting.StickyThresholdMargin != 0.15 || cfg.Meeting.MinAssignDuration != 0.7 {
		t.Errorf("rules = margin %v, duration %v; want 0.15, 0.7", cfg.Meeting.StickyThresholdMargin, cfg.Meeting.MinAssignDuration)
	}
}

func TestWatch_DetectsChangeAndReloads(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	cfg.Meeting.SpeakerThreshold = 0.55
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	got := make(chan *Config, 1)
	stop := Watch(path, 20*time.Millisecond, func(c *Config) {
		got <- c
	})
	defer stop()

	// Must not fire for the file's state as of when Watch started.
	select {
	case <-got:
		t.Fatal("onChange fired before any real change was made")
	case <-time.After(100 * time.Millisecond):
	}

	// Sleep first so the rewritten file gets a strictly later mtime
	// even on filesystems with coarse mtime resolution.
	time.Sleep(20 * time.Millisecond)
	cfg.Meeting.SpeakerThreshold = 0.60
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	select {
	case newCfg := <-got:
		if newCfg.Meeting.SpeakerThreshold != 0.60 {
			t.Errorf("reloaded SpeakerThreshold = %v, want 0.60", newCfg.Meeting.SpeakerThreshold)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("onChange never fired after a real file change")
	}
}

func TestWatch_StopStopsFurtherReloads(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")
	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	var count int32
	stop := Watch(path, 10*time.Millisecond, func(c *Config) {
		atomic.AddInt32(&count, 1)
	})
	stop()

	time.Sleep(20 * time.Millisecond)
	cfg.Meeting.SpeakerThreshold = 0.9
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}
	time.Sleep(100 * time.Millisecond)

	if got := atomic.LoadInt32(&count); got != 0 {
		t.Errorf("onChange fired %d times after stop(), want 0", got)
	}
}

func TestWatch_MissingFileNeverFires(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "does-not-exist.toml")

	var count int32
	stop := Watch(path, 10*time.Millisecond, func(c *Config) {
		atomic.AddInt32(&count, 1)
	})
	defer stop()

	time.Sleep(100 * time.Millisecond)
	if got := atomic.LoadInt32(&count); got != 0 {
		t.Errorf("onChange fired %d times for a nonexistent file, want 0", got)
	}
}

func TestMeetingConfig_VideoHintTiming(t *testing.T) {
	m := MeetingConfig{VideoHintLearnInterval: 0.5, VideoHintCheckInterval: 2}
	learn, check := m.VideoHintTiming()
	if learn != 500*time.Millisecond || check != 2*time.Second {
		t.Errorf("timing = %v, %v; want 500ms, 2s", learn, check)
	}
}

func TestMeetingConfig_VideoHintTiming_FallsBackOnZero(t *testing.T) {
	var m MeetingConfig // zero value
	learn, check := m.VideoHintTiming()
	def := DefaultConfig().Meeting
	if want := time.Duration(def.VideoHintLearnInterval * float64(time.Second)); learn != want {
		t.Errorf("learn = %v, want default %v", learn, want)
	}
	if want := time.Duration(def.VideoHintCheckInterval * float64(time.Second)); check != want {
		t.Errorf("check = %v, want default %v", check, want)
	}
}

func TestMeetingConfig_VideoHintTiming_RecordForTuningLooksDensely(t *testing.T) {
	m := MeetingConfig{VideoHintLearnInterval: 1, VideoHintCheckInterval: 1, RecordForTuning: true}
	if learn, _ := m.VideoHintTiming(); learn != 350*time.Millisecond {
		t.Errorf("learn while recording for tuning = %v, want 350ms", learn)
	}
	m.VideoHintLearnInterval = 0.2 // faster than the tuning rate: kept
	if learn, _ := m.VideoHintTiming(); learn != 200*time.Millisecond {
		t.Errorf("learn = %v, want 200ms", learn)
	}
}
